### ISSUE TITLE
Both logzio-nodejs and winston_logzio doesn't work at all

### ISSUE THREAD

**Issue by han-characters** [logzio/logz-docs#657]
Hi there, basically I just tried out all the code samples on `nodejs` and none of them worked. I tried both `http` and `https` but no luck. 

I just copied and pasted sample codes from the official docs, (of course with my personal token and etc):
https://docs.logz.io/shipping/log-sources/nodejs.html
https://www.npmjs.com/package/winston-logzio

however, it never works. I have been trying to debug on this over 2 weeks. I can even provide my token if you need that. I checked the config line by line but without a working sample, I really had no idea where was wrong.

Can you please help me out here? I think logzio is a great product and I'd like to give it a try, but with non of working codes, I'm at the edge of giving up and go to other similar product. It's really frustrating. 

Here is my simple code (copied directly from docs above):
```
const winston = require('winston');
const LogzioWinstonTransport = require('winston-logzio');

const logzioWinstonTransport = new LogzioWinstonTransport({
  level: 'info',
  name: 'winston_logzio',
  token: '************************',
  host: 'app.logz.io',
});


const logger = winston.createLogger({
    format: winston.format.simple(),
    transports: [logzioWinstonTransport],
});


// setInterval(() => {
//   logger.log('warn', 'Just a test message');
//   console.log(11);
// }, 1000);


var logger2 = require('logzio-nodejs').createLogger({
  token: '************************',
  protocol: 'https',
  host: 'app.logz.io',
  port: '8071',
  type: 'YourLogType'
});


setInterval(() => {
  logger2.log('This is a log message');
  console.log(11);
}, 1000);
```

Here is the error message:
```
logzio-logger error: Error: Failed after 3 retries on error = RequestError: Error: connect ETIMEDOUT 104.124.1.33:8071 Error: Failed after 3 retries on error = RequestError: Error: connect ETIMEDOUT 104.124.1.33:8071
    at /Users/xxxxx/Sites/xxx/xxx-library/node_modules/logzio-nodejs/lib/logzio-nodejs.js:294:46
    at tryCatcher (/Users/xxxxx/Sites/xxx/xxx-library/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/xxxxx/Sites/xxx/xxx-library/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/xxxxx/Sites/xxx/xxx-library/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/xxxxx/Sites/xxx/xxx-library/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/xxxxx/Sites/xxx/xxx-library/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/xxxxx/Sites/xxx/xxx-library/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/xxxxx/Sites/xxx/xxx-library/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/xxxxx/Sites/xxx/xxx-library/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/xxxxx/Sites/xxx/xxx-library/node_modules/bluebird/js/release/async.js:15:14)
    at proces
```

Can you please tell me where is wrong? Also, if possible, I'd like to see a working sample in the real world as I didn't find any resource about it.

`node -v`: `v14.8.0`
`"express": "^4.17.1",`
`"logzio-nodejs": "^2.0.2",`
`"winston": "^3.3.3",`
`"winston-logzio": "^5.1.2"`

Thank you so much.

**Comment by shalper** [comment]
Hi @han-characters, 
Please accept my apologies for the delay. |

The project was recently updated and the guide has been changed to reflect the changes: [https://docs.logz.io/shipping/log-sources/nodejs.html](https://docs.logz.io/shipping/log-sources/nodejs.html
)

I hope your issue has already been resolved, but if it hasn't, please contact our Support for assistance. 
They are always available, 24/7 and extremely responsive.
